### ISSUE TITLE
Provide helm chart binaries via github pages

### ISSUE THREAD

**Issue by sflandergan** [deviceinsight/activemq-artemis-helm#3]
The artemis chart should be downloadable via http as binary, so it can be installed via the helm client.

A good approach can be to use github pages: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417. 

Providing a CI pipeline would be great, but can also be covered in a separate PR

**Comment by pvorb** [comment]
Is this too late for a hacktoberfest contribution? :thinking: :wink:

**Comment by sflandergan** [comment]
next one is probably coming :grin:
